### ISSUE TITLE
URLs instead of URIs

### ISSUE THREAD

**Issue by grenik** [harwey/cups4j#34]
RFC [says](https://tools.ietf.org/html/rfc2911#page-20):
> - Each Printer object is _identified_ with one or more _URIs_.  The
        Printer's "printer-uri-supported" attribute contains the URI(s).

However, you use UR**L**s, not UR**I**s. Since `ipp://` is not a valid protocol for a `java.net.URL` class, you simply [replace](https://github.com/harwey/cups4j/search?q=replace+http+ipp&unscoped_q=replace+http+ipp) `ipp` with `http`. This is already error-prone since some printers URIs have `ipps://` protocol and you fail to process them.

To prove the issue, you can call `getDefaultPrinter()` on a cups client with `127.0.0.1` as host and `631` as port. You will get the following error:
```
java.net.MalformedURLException: unknown protocol: ipps
	at java.net.URL.<init>(URL.java:618)
	at java.net.URL.<init>(URL.java:508)
	at java.net.URL.<init>(URL.java:457)
	at org.cups4j.operations.cups.CupsGetDefaultOperation.getDefaultPrinter(CupsGetDefaultOperation.java:62)
	at org.cups4j.CupsClient.getDefaultPrinter(CupsClient.java:154)
```

If you use `localhost` as the host, you won't get an error.

In addition to that, I see that to compare two URLs you call `toString()` on them and [compare the resulting strings](https://github.com/harwey/cups4j/blob/f770f705135ddbc576670daee44250a01eb3a01a/src/main/java/org/cups4j/CupsClient.java#L173) which doesn't seem right. Maybe you are doing the comparison this way because `equals` cannot be used on `java.net.URL` since it has some issues (tries to resolve the hostname to an IP address).

Since URIs [in IPP](https://tools.ietf.org/html/rfc2911#section-4.1.5) have the same meaning as [`java.net.URI`](https://docs.oracle.com/javase/7/docs/api/java/net/URI.html) in Java (they both conform to RFC2396), I suggest that you switch to `java.net.URI`. You won't have issues with `ipp(s)` protocol and could also use `equals()` to compare them because it is not broken as in `java.net.URL`.

**Comment by harwey** [comment]
Hi Nikolay,
this seem reasonable to me. I iwll take a look - hopefully soon. I sadly don't have much time for Cups4j, and with Corona around things don't get better. 
I will try to look at this soon.
Thanks for your message!
Harald

**Comment by gmuth** [comment]
I can't provide a fix for this library, but a potential solution for your use case, grenik: With Corona around I had time to reimplement a new IppClient from scratch in Kotlin that supports `ipps` and also includes a [CupsClient](https://github.com/gmuth/ipp-client-kotlin/blob/master/src/main/kotlin/de/gmuth/ipp/cups/CupsClient.kt).

**Comment by oboehm** [comment]
v0.8.0 supports now HTTPS and IPPS.
